# Generated by Django 4.0.1 on 2022-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_maths_mathseasy_mathshard_mathsmedium_physics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemistry_hard', models.IntegerField()),
                ('chemistry_easy', models.IntegerField()),
                ('chemistry_medium', models.IntegerField()),
            ],
        ),
    ]
