# Generated by Django 4.0.1 on 2022-03-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_resultchemistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultMaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths_hard', models.IntegerField()),
                ('maths_easy', models.IntegerField()),
                ('maths_medium', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultPhysics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics_hard', models.IntegerField()),
                ('physics_easy', models.IntegerField()),
                ('physics_medium', models.IntegerField()),
            ],
        ),
    ]
