# Generated by Django 4.0.1 on 2022-03-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0004_resultmaths_resultphysics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPhysicsFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics_hard', models.IntegerField()),
                ('physics_easy', models.IntegerField()),
                ('physics_medium', models.IntegerField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
