# Generated by Django 4.0.1 on 2022-03-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_resultphysicsfirst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultChemistry',
        ),
        migrations.DeleteModel(
            name='ResultMaths',
        ),
        migrations.DeleteModel(
            name='ResultPhysics',
        ),
        migrations.DeleteModel(
            name='ResultPhysicsFirst',
        ),
    ]
