# Generated by Django 4.0.1 on 2022-03-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_resultphysics_resultmaths_resultchemistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmaths',
            name='maths_easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultmaths',
            name='maths_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultmaths',
            name='maths_medium',
            field=models.IntegerField(default=0),
        ),
    ]
